<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Dovetail.Engine</RootNamespace>
    <AssemblyName>dovetail-engine</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Product>Dovetail</Product>
    <AssemblyTitle>Dovetail Translation Engine Host</AssemblyTitle>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dovetail.Core\Dovetail.Core.csproj" />
  </ItemGroup>

</Project>
